name: Deploy

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    # workwaround for cannot set timezone, cron will start on UTC+8 21:00
    - cron: "0 15 * * *"
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Whether to deploy to gh-pages branch'
        required: true
        default: '0'

env:
  TZ: Asia/Taipei

jobs:
  download:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: sudo apt-get install curl wget jq git -y --no-install-recommends
      - name: Download
        run: ./download.sh
      - name: Deploy
        if: ${{ github.event_name == 'schedule' || github.event.inputs.deploy == '1' }}
        run: |
          # update gh-pages
          git clone https://github.com/${{ github.repository }}.git -b gh-pages --depth 1 --single-branch gh-pages
          cp -rf dist/* gh-pages
          # push to gh-pages
          cd gh-pages
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "$(date +%Y%m%d)" || true
          git push https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
